import streamlit as st
from transformers import pipeline
from fpdf import FPDF
from docx import Document
import pandas as pd
import datetime
import io
import os

# ----------------------------------------------------
# 💡 Load summarizer model (lightweight + CPU friendly)
# ----------------------------------------------------
@st.cache_resource
def load_summarizer():
    return pipeline("summarization", model="sshleifer/distilbart-cnn-12-6")

summarizer = load_summarizer()

# ----------------------------------------------------
# 📄 Extract text from uploaded files
# ----------------------------------------------------
def extract_text_from_file(uploaded_file):
    """Extract readable text from uploaded file based on extension."""
    file_name = uploaded_file.name.lower()

    # ✅ TXT files
    if file_name.endswith(".txt"):
        try:
            raw_bytes = uploaded_file.getvalue()
            text = raw_bytes.decode("utf-8", errors="ignore")
            return text.strip()
        except Exception as e:
            return f"⚠️ Error reading TXT file: {e}"

    # ✅ DOCX files
    elif file_name.endswith(".docx"):
        try:
            doc = Document(uploaded_file)
            return "\n".join([para.text for para in doc.paragraphs])
        except Exception as e:
            return f"⚠️ Error reading DOCX file: {e}"

    # ✅ XLSX files
    elif file_name.endswith(".xlsx"):
        try:
            df = pd.read_excel(uploaded_file)
            return df.to_string(index=False)
        except Exception as e:
            return f"⚠️ Error reading XLSX file: {e}"

    # ✅ CSV files
    elif file_name.endswith(".csv"):
        try:
            df = pd.read_csv(uploaded_file)
            return df.to_string(index=False)
        except Exception as e:
            return f"⚠️ Error reading CSV file: {e}"

    # ❌ Unsupported file
    return "⚠️ Unsupported file format."


# ----------------------------------------------------
# 🧾 Unicode-safe PDF generator
# ----------------------------------------------------
class PDFUnicode(FPDF):
    def header(self):
        self.set_font("Arial", "B", 18)
        self.cell(0, 10, "DataDigest Summary Report", ln=True, align="C")
        self.ln(5)

def generate_pdf_report(summaries):
    """Create a clean, emoji-free, Unicode-safe PDF summary."""
    pdf = PDFUnicode()
    pdf.add_page()

    pdf.set_font("Arial", "I", 11)
    pdf.cell(0, 10, f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=True)
    pdf.ln(8)

    for file_name, summary in summaries.items():
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, f"File: {file_name}", ln=True)
        pdf.ln(3)

        pdf.set_font("Arial", "", 12)
        # Remove unsupported characters (like emojis)
        clean_summary = "".join(ch for ch in summary if ord(ch) < 256)
        pdf.multi_cell(0, 8, clean_summary)
        pdf.ln(8)
        pdf.cell(0, 0, "-" * 100, ln=True)
        pdf.ln(8)

    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 10, "Report generated by DataDigest AI Summarizer", ln=True, align="C")

    output_path = os.path.join(os.getcwd(), "DataDigest_Summary_Report.pdf")
    pdf.output(output_path, "F")
    return output_path


# ----------------------------------------------------
# 🎯 Streamlit UI
# ----------------------------------------------------
st.set_page_config(page_title="DataDigest", page_icon="📊")
st.title("📊 DataDigest – AI File Summarizer")

st.write("Upload your text, Word, Excel, or CSV files below to generate summarized reports.")

# ✅ Upload multiple files directly (single option)
uploaded_files = st.file_uploader(
    "Upload .txt, .docx, .xlsx, or .csv files",
    type=["txt", "docx", "xlsx", "csv"],
    accept_multiple_files=True
)

# ----------------------------------------------------
# 🚀 Generate Summary Button
# ----------------------------------------------------
if st.button("Generate Summary Report"):
    if not uploaded_files:
        st.warning("⚠️ Please upload at least one file first.")
    else:
        summaries = {}
        st.info("⏳ Processing files... Please wait...")

        for uploaded_file in uploaded_files:
            text = extract_text_from_file(uploaded_file)

            # Skip if empty or unreadable
            if not text or "⚠️" in text or len(text.strip()) == 0:
                summaries[uploaded_file.name] = "⚠️ File appears empty or unreadable."
                continue

            try:
                # Summarize any text length safely
                summary = summarizer(
                    text[:3000],  # Trim to 3000 chars for safety
                    max_length=180,
                    min_length=40,
                    do_sample=False
                )[0]["summary_text"]
                summaries[uploaded_file.name] = summary
            except Exception as e:
                summaries[uploaded_file.name] = f"⚠️ Error during summarization: {str(e)}"

        st.success("✅ Summaries generated successfully!")

        report_path = generate_pdf_report(summaries)
        with open(report_path, "rb") as f:
            st.download_button("📥 Download PDF Report", f, file_name="DataDigest_Summary_Report.pdf")

        st.write("### 📝 Summaries Preview:")
        for file_name, summary in summaries.items():
            st.write(f"**{file_name}**")
            st.write(summary)
            st.write("---")

